// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"processon/internal/app/server/dao/internal"
)

// internalCheckJobDao is internal type for wrapping internal DAO implements.
type internalCheckJobDao = *internal.CheckJobDao

// checkJobDao is the data access object for table check_job.
// You can define custom methods on it to extend its functionality as you wish.
type checkJobDao struct {
	internalCheckJobDao
}

var (
	// CheckJob is globally public accessible object for table check_job operations.
	CheckJob = checkJobDao{
		internal.NewCheckJobDao(),
	}
)

// Fill with you ideas below.
