// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"processon/internal/app/server/dao/internal"
)

// internalCheckScriptDao is internal type for wrapping internal DAO implements.
type internalCheckScriptDao = *internal.CheckScriptDao

// checkScriptDao is the data access object for table check_script.
// You can define custom methods on it to extend its functionality as you wish.
type checkScriptDao struct {
	internalCheckScriptDao
}

var (
	// CheckScript is globally public accessible object for table check_script operations.
	CheckScript = checkScriptDao{
		internal.NewCheckScriptDao(),
	}
)

// Fill with you ideas below.
